# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]  # needed if you have custom yaml tags anywhere
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: detect-private-key       # catches accidentally committed keys — cheap insurance
      - id: mixed-line-ending


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py314-plus]  # match your actual target version

  - repo: https://github.com/pycqa/isort
    rev: 9.0.0b5
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.11
    hooks:
      - id: djhtml

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-pyproject"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]
