"""fullfillment_data

Revision ID: 3ac57f3707a9
Revises: 1c2d3e4f5a6b
Create Date: 2026-07-13 01:55:34.044561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ac57f3707a9"
down_revision = "1c2d3e4f5a6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fulfillment_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_column("fulfillment_data")

    # ### end Alembic commands ###
