"""multi_currency_price_columns

Revision ID: 3e18224c09e3
Revises: 54a26461c56b
Create Date: 2026-05-17 19:38:06.289798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e18224c09e3'
down_revision = '54a26461c56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minute_packs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='CLP'))
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='CLP'))
        batch_op.alter_column('unit_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='CLP'))
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='CLP'))
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=19, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('currency')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('currency')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('currency')

    with op.batch_alter_table('minute_packs', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=19, scale=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
