"""payments.extra_data

Revision ID: 3fe44943e8c1
Revises: b57d52cba819
Create Date: 2026-03-14 22:02:58.863274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe44943e8c1'
down_revision = 'b57d52cba819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_payments', schema=None) as batch_op:
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###
