"""model defaults

Revision ID: 54a26461c56b
Revises: c19e884a175c
Create Date: 2026-05-17 18:31:58.424336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54a26461c56b'
down_revision = 'c19e884a175c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
