"""minute_pack.slug

Revision ID: 572019ee478c
Revises: a7b8c9d0e1f2
Create Date: 2026-06-03 21:54:42.051658

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "572019ee478c"
down_revision = "a7b8c9d0e1f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("minute_packs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f("ix_minute_packs_slug"), ["slug"], unique=False)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("payment_status", existing_type=mysql.VARCHAR(length=32), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("payment_status", existing_type=mysql.VARCHAR(length=32), nullable=True)

    with op.batch_alter_table("minute_packs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_minute_packs_slug"))
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
