"""add template_name to static_pages

Revision ID: 7b79db108ac7
Revises: b0c8fb6799b2
Create Date: 2026-03-10 23:22:30.862490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b79db108ac7'
down_revision = 'b0c8fb6799b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.drop_column('template_name')

    # ### end Alembic commands ###
