"""minute_pack.slug unique

Revision ID: 8591bbe22224
Revises: 572019ee478c
Create Date: 2026-06-03 21:55:19.119679

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8591bbe22224"
down_revision = "572019ee478c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("minute_packs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_minute_packs_slug"))
        batch_op.create_index(batch_op.f("ix_minute_packs_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("minute_packs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_minute_packs_slug"))
        batch_op.create_index(batch_op.f("ix_minute_packs_slug"), ["slug"], unique=False)

    # ### end Alembic commands ###
