"""firenze audit

Revision ID: 8918248ea857
Revises: 3e18224c09e3
Create Date: 2026-05-18 22:13:21.807881

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8918248ea857"
down_revision = "3e18224c09e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "firenze_payload",
                sa.JSON(),
                server_default=sa.text("'{}'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "firenze_response",
                sa.JSON(),
                server_default=sa.text("'{}'"),
                nullable=False,
            )
        )
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=255), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=255), nullable=False)
        batch_op.drop_column("firenze_response")
        batch_op.drop_column("firenze_payload")

    # ### end Alembic commands ###
