"""add missing flask_security columns to users and roles

Revision ID: 94e7006cd47f
Revises: a9b8c7d6e5f4
Create Date: 2026-05-05 16:28:31.763945

"""

import sqlalchemy as sa
from alembic import op
from flask_security import AsaList
from sqlalchemy.ext.mutable import MutableList

# revision identifiers, used by Alembic.
revision = "94e7006cd47f"
down_revision = "a9b8c7d6e5f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("permissions", MutableList.as_mutable(AsaList()), nullable=True))
        batch_op.add_column(
            sa.Column("update_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confirmed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("current_login_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_login_ip", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("current_login_ip", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("login_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("tf_primary_method", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("tf_totp_secret", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("tf_phone_number", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("us_totp_secrets", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("us_phone_number", sa.String(length=128), nullable=True))
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=80), type_=sa.String(length=255), existing_nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=256), type_=sa.String(length=255), nullable=True
        )
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.create_unique_constraint("uq_users_username", ["username"])
        batch_op.create_unique_constraint("uq_users_us_phone_number", ["us_phone_number"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_us_phone_number", type_="unique")
        batch_op.drop_constraint("uq_users_username", type_="unique")
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=1)
        batch_op.alter_column(
            "password", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=256), nullable=False
        )
        batch_op.alter_column(
            "username", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=80), existing_nullable=True
        )
        batch_op.drop_column("us_phone_number")
        batch_op.drop_column("us_totp_secrets")
        batch_op.drop_column("tf_phone_number")
        batch_op.drop_column("tf_totp_secret")
        batch_op.drop_column("tf_primary_method")
        batch_op.drop_column("login_count")
        batch_op.drop_column("current_login_ip")
        batch_op.drop_column("last_login_ip")
        batch_op.drop_column("current_login_at")
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("confirmed_at")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_column("update_datetime")
        batch_op.drop_column("permissions")

    # ### end Alembic commands ###
