"""add discount codes

Revision ID: abcdef123456
Revises: 8f4a6b9c2d10
Create Date: 2026-07-13 06:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abcdef123456"
down_revision = "3ac57f3707a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("discount_type", sa.String(length=20), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("uses_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discount_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discount_codes_code"), ["code"], unique=True)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discount_code_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("applied_discount_code", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("discount_amount", sa.Numeric(precision=19, scale=4), nullable=True))
        batch_op.create_foreign_key("fk_orders_discount_code_id", "discount_codes", ["discount_code_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint("fk_orders_discount_code_id", type_="foreignkey")
        batch_op.drop_column("discount_amount")
        batch_op.drop_column("applied_discount_code")
        batch_op.drop_column("discount_code_id")

    with op.batch_alter_table("discount_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discount_codes_code"))

    op.drop_table("discount_codes")
    # ### end Alembic commands ###
