"""add user profile fields and payments table

Revision ID: b0c8fb6799b2
Revises: a1b2c3d4e5f6
Create Date: 2026-02-26 02:26:09.338512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c8fb6799b2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('redirect_url', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('rut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('commune', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_payment', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_payment')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('commune')
        batch_op.drop_column('address')
        batch_op.drop_column('rut')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_session_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
