"""WebPush client_id not nullable

Revision ID: b1c5699834a0
Revises: c6ad83777539
Create Date: 2026-07-18 23:48:47.994900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c5699834a0'
down_revision = 'c6ad83777539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('client_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('client_id'), ['client_id'], unique=True)

    # ### end Alembic commands ###
