"""Add trusted_until field for passwordless signin trust window

Revision ID: b54236434b59
Revises: 94e7006cd47f
Create Date: 2026-05-05 22:34:04.900162

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "b54236434b59"
down_revision = "94e7006cd47f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=32), nullable=False)
        batch_op.alter_column(
            "extra_args", existing_type=sqlite.JSON(), nullable=False, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "request_payload", existing_type=sqlite.JSON(), nullable=False, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "response_payload", existing_type=sqlite.JSON(), nullable=False, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "payment_object", existing_type=sqlite.JSON(), nullable=False, existing_server_default=sa.text("'{}'")
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trusted_until", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("trusted_until")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "payment_object", existing_type=sqlite.JSON(), nullable=True, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "response_payload", existing_type=sqlite.JSON(), nullable=True, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "request_payload", existing_type=sqlite.JSON(), nullable=True, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column(
            "extra_args", existing_type=sqlite.JSON(), nullable=True, existing_server_default=sa.text("'{}'")
        )
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=32), nullable=True)

    # ### end Alembic commands ###
