"""flask_merchants

Revision ID: b57d52cba819
Revises: e1f2a3b4c5d6
Create Date: 2026-03-14 21:19:42.627920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b57d52cba819'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fm_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchants_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('extra_args', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('request_payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('response_payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('payment_object', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fm_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fm_payments_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_fm_payments_merchants_id'), ['merchants_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fm_payments_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_fm_payments_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_fm_payments_transaction_id'), ['transaction_id'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_session_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('redirect_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=False),
    sa.Column('state', sa.VARCHAR(length=32), nullable=False),
    sa.Column('metadata_json', sqlite.JSON(), nullable=False),
    sa.Column('request_payload', sqlite.JSON(), nullable=False),
    sa.Column('response_payload', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_session_id'), ['session_id'], unique=1)

    with op.batch_alter_table('fm_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fm_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_fm_payments_state'))
        batch_op.drop_index(batch_op.f('ix_fm_payments_provider'))
        batch_op.drop_index(batch_op.f('ix_fm_payments_merchants_id'))
        batch_op.drop_index(batch_op.f('ix_fm_payments_email'))

    op.drop_table('fm_payments')
    # ### end Alembic commands ###
