"""add static_pages table

Revision ID: c3234ec13c39
Revises: f4b6cd3e1d22
Create Date: 2026-02-25 01:22:32.209738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3234ec13c39'
down_revision = 'f4b6cd3e1d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_pages_path'), ['path'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_pages_path'))

    op.drop_table('static_pages')
    # ### end Alembic commands ###
